### ISSUE TITLE
Minimum Java Version - Seems it needs to be 21+ ?  (SequencedCollection Class Needed)

### ISSUE THREAD

**Issue by devcarbon-com** [fractl-io/fractl#1259]
It appears that SequencedCollection was added in Java 21: https://openjdk.org/jeps/431

With Java 17, `fractl build` dies with:

```sh
 $ fractl build
NOTE: Picked up JDK_JAVA_OPTIONS: -Dlogback.configurationFile=/path/to/logback.xml
NOTE: Picked up JDK_JAVA_OPTIONS: -Dlogback.configurationFile=/path/to/logback.xml
Generating fresh 'lein new' fractl-model project.
no build -> client spec in config, skipping client-app generation
NOTE: Picked up JDK_JAVA_OPTIONS: -Dlogback.configurationFile=/path/to/logback.xml
NOTE: Picked up JDK_JAVA_OPTIONS: -Dlogback.configurationFile=/path/to/logback.xml
Compiling hello.core
Syntax error macroexpanding at (core.cljc:1:1).
Execution error (ClassNotFoundException) at jdk.internal.loader.BuiltinClassLoader/loadClass (BuiltinClassLoader.java:641).
java.util.SequencedCollection

Full report at:
/var/folders/zl/tyjfph_92ws1z65_7mbtbdxc0000gn/T/clojure-182847631716320706.edn
Compilation failed: Subprocess failed (exit code: 1)
Exception in thread "main" org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
``` 

But the readme (currently) reads:
> JVM 11 or later (JVM 19+ recommended)

Or perhaps there is something else I'm missing?

Thanks in advance.

**Comment by pratik-fractl** [comment]
Hi @devcarbon-com. Thanks for raising this issue! 🙏 

Yes, we need Java 21+. Will update the `README` ASAP.
